name: Build and Publish Docker

on:
  push:
    branches:
      - master
    tags:
      - v1.*
      - v2.*
      - v3.*
      
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Build/release Electron app
        run: |
          yarn install
          yarn rebuild
          yarn build:win