name: Build and Publish Docker

on:
  push:
    branches:
      - master
    tags:
      - v1.*
      - v2.*
      - v3.*
      
jobs:
  release:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out branch
        uses: actions/checkout@master
        
      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 10
        
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.token }}
        run: |
          npm install
          npm run rebuild
          npm run build
      - name: Compress Bundle
        run: |
          npm install -g bestzip
          bestzip Pos-Vue-win32-x64.zip  build/win-unpacked/*
      - name: Upload Win Package
        uses: actions/upload-artifact@v1
        with:
          name: Windows_Dist
          path: Pos-Vue-win32-x64.zip
          